### ISSUE TITLE
 TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by nitaking** [otoyo/easy-notion-blog#42]
## 発生していること

2b92639dd77b5b6c6522a6daf29438092e529198 辺りでは起きなかったように思うのですが、現在masterの 95da4a5 で `yarn dev` を実行したところ、以下のエラーが発生します。

```shell
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at Header (webpack-internal:///./src/components/header.tsx:24:17)
    at processChild (/Users/user2/code/easy-notion-blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/user2/code/easy-notion-blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/user2/code/easy-notion-blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/user2/code/easy-notion-blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/Users/user2/code/easy-notion-blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/Users/user2/code/easy-notion-blog/node_modules/next/dist/server/render.js:736:46) {
  input: '/_next/static/webpack/07ea94bbe1acf6f4.webpack.hot-update.json',
  code: 'ERR_INVALID_URL'
}
```

## 再現手順
1. `git clone https://github.com/otoyo/easy-notion-blog`
2. `yarn install`
3. `yarn dev`

※厳密には、forkした https://github.com/nitaking/easy-notion-blog にて fork元の最新化を行った際に事象は発生しました

## 解決策
1. `env.local` に 以下を追加（READMEに加筆）

```env
NEXT_PUBLIC_URL=http://localhost:3000/
```

2. `NEXT_PUBLIC_URL`のデフォルト値を設定

私としては `2. `NEXT_PUBLIC_URL`のデフォルト値を設定` が適切かな、と思うのでそちらで[draft PR](#44)を作成しておきます。対応方針ご相談したいです！

**Comment by otoyo** [comment]
ご報告ありがとうございます。
最近の変更でナビゲーションバーや document head でカレントURLを取得するロジックを `NEXT_PUBLIC_URL` 依存にしてしまったのが原因だと思います（下記）。
https://github.com/otoyo/easy-notion-blog/blob/e5ad20f6fd7896d8d5884bf24920312623716fc5/src/components/document-head.tsx#L13
https://github.com/otoyo/easy-notion-blog/blob/e5ad20f6fd7896d8d5884bf24920312623716fc5/src/components/header.tsx#L16

もともと `NEXT_PUBLIC_URL` の有無でソーシャルボタンの表示を制御していたので（下記）、修正方針としては上記2箇所でデフォルトの値 `http://localhost:3000` を設定したいと思います。
https://github.com/otoyo/easy-notion-blog/blob/e5ad20f6fd7896d8d5884bf24920312623716fc5/src/pages/blog/%5Bslug%5D.tsx#L114
https://github.com/otoyo/easy-notion-blog/blob/e5ad20f6fd7896d8d5884bf24920312623716fc5/README.ja.md?plain=1#L118-L119

せっかく PR 作っていただいたのにすみません。こちらは自分の方で修正してしまいます。

**Comment by otoyo** [comment]
https://github.com/otoyo/easy-notion-blog/pull/45 で修正しましたのでご確認ください。
`NEXT_PUBLIC_URL` のデフォルト値を設定してしまうと本番環境で URL が意図しない値となってしまうため、`NEXT_PUBLIC_URL` 依存箇所はオプトイン形式に変更しました。

**Comment by nitaking** [comment]
@otoyo 
早速の対応ありがとうございます！オプトイン形式が自然ですね。修正ありがとうございました！
